### ISSUE TITLE
folder structure

### ISSUE THREAD

**Issue by thartbm** [Intrepid-2a/Calibration#1]
Currently this data to not be in a sub-folder of the code, for better separation of code from data.

Change this? There are work-arounds to keep data not on GitHub, but I find avoiding the possibility from the start is cleaner.

**Comment by thartbm** [comment]
Working on this. It's implemented in the EyeTracker repo and Distance task, but not yet in the Calibration tasks.

**Comment by ClementAbb** [comment]
I don't find the folder structure obvious right now, could we have it explicitly e.g. on the project's README?

**Comment by thartbm** [comment]
Info added on Runner readme, function to set up folder structure is in Runner/utilities, working on returning all paths from localizeSetup() function.
