### ISSUE TITLE
col_both

### ISSUE THREAD

**Issue by thartbm** [Intrepid-2a/Calibration#3]
Updated the value in blind spot mapping, but should it even be used?

**Comment by ClementAbb** [comment]
I will be very similar to black but I would still prefer it over black whenever we want to use black (fixation, fusion stim...). On a similar note I would use col_back instead of white (e.g. the other color for fusion stim).

**Comment by thartbm** [comment]
I guess col_both is not too far from black, so I'll put it back.

**Comment by thartbm** [comment]
Which stimuli should use col_both?

**Comment by ClementAbb** [comment]
Fixation and fusion stim at least. Instruction and any other text probably.

**Comment by thartbm** [comment]
We should also decide on an implementation / definition of that color.

The last distance task set it as `[-0.7, -0.7, -0.7]` but previously it was `[eval(col_param[3])[1], eval(col_param[5])[0], -1]` in the blind spot mapping task, which boils down to roughly `[-0.5, -0.5, -1]` (apart from some small location-based differences).

For now, I'll set it to the previous value from the blind spot mapping task in the localizeSetup thing, and this can be easily changed. But we should not have diverging implementations of these colors across experimental tasks and calibration tasks.

**Comment by thartbm** [comment]
I'd made a colors dictionary before anyway, to pass to the eye-tracker object to able to set calibration stimulus properties, so just making that in 1 spot, and using it everywhere will be the simplest solution.

**Comment by thartbm** [comment]
Seems done.
