### ISSUE TITLE
step-size / pyglet keyboard

### ISSUE THREAD

**Issue by thartbm** [Intrepid-2a/Calibration#4]
In order for people to smoothly move the blind spot marker around and resize it, I'm using the pyglet keyboard system where you can hold down a key to keep changing in that direction / dimension. This also allows greatly reducing the step size (from 0.5 dva to 0.01) so if you don't hold down the key you can make tiny adjustments and we can get very precise blind spot mapping.

Apparently this does not work in Glasgow?

**Comment by thartbm** [comment]
I've increased the step size to 0.25 dva for now, but that means the marker flies of the screen here.

**Comment by ClementAbb** [comment]
Fair enough for holding the key. I started another discussion about step size and how it seems to work differently here.

**Comment by thartbm** [comment]
Yes, puzzling. I've closed the other thread, with a higher stepsize for now. But I might have different step sizes for Glasgow and Toronto later on. Not important enough to figure out why IMO, so if you're OK with a hacky solution like that I'll make that change later on.
